name: Update readme ⭐️ progress

on:
  push:
    branches: [main]

jobs:
    update-readme:
      strategy:
        matrix:
          year:
            #- 2022
            #- 2023
            #- 2024
            - 2025
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v6
          - uses: k2bd/advent-readme-stars@v1
            with:
                userId: ${{ secrets.AOC_USER_ID }}
                sessionCookie: ${{ secrets.AOC_SESSION }}
                year: ${{ matrix.year }}
                readmeLocation: ${{ matrix.year }}/README.md
          - uses: stefanzweifel/git-auto-commit-action@v5
            with:
              commit_message: "chore(${{ matrix.year }}): update readme progess"
